# Generated by Django 5.1.3 on 2024-11-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoestado',
            old_name='num_control',
            new_name='numero_control',
        ),
    ]
